# runtime: nodejs22
# handlers:
#   - url: /(.*\..+)$
#     static_files: build/\1
#     upload: build/(.*\..+)$
#   - url: /.*
#     static_files: build/index.html
#     upload: build/index.html

runtime: nodejs22
instance_class: F1
env: standard

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    script: auto